version: '2'
services:
  redis-1:
    image: redis:3
    ports:
      - "6371:6379"
  redis-2:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6372:6379"
  redis-3:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6373:6379"
  sentinel-1:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=10000
      - SENTINEL_FAILOVER=26000
    ports:
      - "26000:26000"
  sentinel-2:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=10000
      - SENTINEL_FAILOVER=27000
    ports:
      - "27000:27000"

  sentinel-3:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=10000
      - SENTINEL_FAILOVER=28000
    ports:
      - "28000:28000"
